FROM astrocrpublic.azurecr.io/runtime:3.0-2
# FROM quay.io/astronomer/astro-runtime:13.0.0

# RUN python -m venv dbt_venv && source dbt_venv/bin/activate && \
#     pip install --no-cache-dir dbt-snowflake && deactivate
